### ISSUE TITLE
Overlapping

### ISSUE THREAD

**Issue by etunni** [TypeResources/typeresources.github.io#11]
At small sizes overlapping the font and your name below.

![screen shot 2016-07-06 at 07 59 53](https://cloud.githubusercontent.com/assets/5973399/16615842/b221110a-434f-11e6-8679-e888ce4737f8.png)

**Comment by tderkert** [comment]
@etunni Should not overlap ascenders now but your example looks like it's overlapping baseline. How does it look now? Can you turn on guidelines and show how that looks?

**Comment by etunni** [comment]
Great!
![screen shot 2016-07-06 at 08 30 24](https://cloud.githubusercontent.com/assets/5973399/16616506/0be3ce36-4354-11e6-9ca7-984d404caadd.png)

**Comment by tderkert** [comment]
No problem!

**Comment by tderkert** [comment]
@etunni And thank you for the heads up.
