### ISSUE TITLE
Quoteright

### ISSUE THREAD

**Issue by etunni** [TypeResources/typeresources.github.io#12]
The quotes are showed as name.
![quoteright issue](https://cloud.githubusercontent.com/assets/5973399/16617436/11eb2e68-435a-11e6-83a6-9f6dcd7a84a4.png)

**Comment by tderkert** [comment]
Thanks for the feedback!
This is most likely a problem in the Glyphs script that doesn't convert the string properly. Feel free to open an issue in that repo instead, or I can do it for you. And if you have suggestions for solutions we're happy to hear them.
