### ISSUE TITLE
Reset URL parameters on state change

### ISSUE THREAD

**Issue by tderkert** [TypeResources/typeresources.github.io#13]
Remove url parameters on state change to avoid problems on reload etc.

**Comment by etunni** [comment]
I don't understand that I need to do.

**Comment by tderkert** [comment]
**Problem 1:**
1. You have loaded Glyph Gazer with url parameters with lets say: `?text=mytext`. Maybe using Launch Glyph Gazer script in Glyphs.
2. You make some change to the text string with the page GUI.
3. Your reload the page. Your changes are overridden.

**Problem 2:**
1. You have made some changes on page
2. You press URL-generator button
3. You make some additional changes
4. You could mistakenly assume that the changes are included in the url.

I think it's better to remove to url parameters and only show them when you generate the sharable URL. Mostly to keep it simple and avoid confusions.

**Comment by etunni** [comment]
This is the code that I have:

```
#MenuTitle: Launch Glyph Gazer
''' Open text content of currently open tab with Glyph Gazer web tool'''
import urllib   
import webbrowser

# Variables
baseUrl = "https://typeresources.github.io/glyph-gazer/?text="


# Get text content of currently open tab in Glyphs
currentText = Glyphs.font.currentText

# Convert encoding to UTF-8
currentTextUTF8 = currentText.encode('UTF-8','strict')

# URL escape string
encodedTextQuery = urllib.quote(currentTextUTF8)

# Create full URL
url = baseUrl+encodedTextQuery

# Open URL in browser
webbrowser.open(url)
```

**Comment by tderkert** [comment]
@etunni I think you're are writing in the wrong issue. That code is for the Glyphs App script and is separate from the Glyph Gazer tool. I closed your [previous issue](https://github.com/TypeResources/typeresources.github.io/issues/12) (which was a very valid issue, just in the wrong repo). I would appreciate if you opened a new issue in [Glyphs-Script repo](https://github.com/TypeResources/Glyphs-Scripts/issues).

**Comment by tderkert** [comment]
Added `clearUrl` function and added it to all UI interaction. It would be prettier and more maintainable If we could listen on state changes somehow and then reset the URL, instead of hard coded to all UI event listeners specifically.
