### ISSUE TITLE
Only update url params when user starts editing

### ISSUE THREAD

**Issue by larsenwork** [TypeResources/typeresources.github.io#6]
Seems a bit bloated that a new visitor sees `?text=Adhesion&fonts=Open%20Sans,Roboto:900,Source%20Sans%20Pro:200&textAlign=center&openType=frac` without having made a single edit. This could be solved by #5 though.

**Comment by tderkert** [comment]
That breaks some of the idea of the sharing function. Let's break it out to a link/share button instead and keep url clean until user wants to share.

**Comment by larsenwork** [comment]
Share button implemented. Closes this.
