### ISSUE TITLE
Force all Open Type Features to be off as default

### ISSUE THREAD

**Issue by tderkert** [TypeResources/typeresources.github.io#9]
Update styles so that the browser/system default features are always off, unless added in the Open Type input.

**Comment by tderkert** [comment]
Tried to disable 'liga' for body but since the features are set in the same attribute it all gets overridden by what ever is set to the gaze-container. So we'll need to set the ones we want off explicitly.

If we know it's only 'liga' that is set as 'on' as default we can just check for that spcifically and  always set that to 'off' unless it's in the state list of features.

**Comment by larsenwork** [comment]
Browsers behave very differently here (again) so we might as well stick with our - what-does-chrome-do approach

**Comment by tderkert** [comment]
We could probably use [Impallaris testing tool implementation](https://github.com/impallari/Font-Testing-Page/blob/master/js/otfeatures-v9.1.js) as a base to improve this feature. Will look into it later.

**Comment by etunni** [comment]
Hi, could be great!!

Cheers,
Eduardo Tunni

**Comment by tderkert** [comment]
Did a quick solution just adding ', "kern" off' at the end of the string if `kern` doesn't exist as a substring. Same for `liga` and `calt`.
